1. Import Pandas

In [99]:
import pandas as pd

2. Read csv

In [100]:
df = pd.read_csv("data.csv")

3. view 1st rows

In [101]:
df.head()

,Employee_ID,Name,Age,City,Department,Salary,Experience_Years,Performance_Score,Join_Date,Gender
0,1,Aarav,23.0,Hyderabad,IT,52000.0,2,78.0,2026-01-12,Male
1,2,Diya,25.0,Bengaluru,HR,48000.0,3,84.0,2026-01-15,Female
2,3,Rohan,28.0,Pune,Finance,65000.0,5,91.0,2026-02-01,Male
3,4,Meera,24.0,Hyderabad,IT,56000.0,2,88.0,2026-02-03,Female
4,5,Arjun,31.0,Chennai,Sales,72000.0,7,76.0,2026-02-10,Male

4. view last rows

In [102]:
df.tail()

,Employee_ID,Name,Age,City,Department,Salary,Experience_Years,Performance_Score,Join_Date,Gender
36,37,Aryan,27.0,Bengaluru,Sales,60500.0,4,82.0,2026-07-15,Male
37,38,Shruti,29.0,Hyderabad,HR,56500.0,5,88.0,2026-07-18,Female
38,39,Rakesh,52.0,Chennai,Management,500000.0,27,97.0,2026-07-22,Male
39,40,Divya,24.0,Pune,IT,55000.0,2,84.0,2026-07-29,Female
40,40,Divya,24.0,Pune,IT,55000.0,2,84.0,2026-07-29,Female

5. Check shape

In [103]:
df.shape

(41, 10)

6. Check columns

In [104]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'City', 'Department', 'Salary',
       'Experience_Years', 'Performance_Score', 'Join_Date', 'Gender'],
      dtype='object')

7. Check Data types

In [105]:
df.dtypes

Employee_ID            int64
Name                  object
Age                  float64
City                  object
Department            object
Salary               float64
Experience_Years       int64
Performance_Score    float64
Join_Date             object
Gender                object
dtype: object

8. Dataset info

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        41 non-null     int64
 1   Name               41 non-null     object
 2   Age                40 non-null     float64
 3   City               40 non-null     object
 4   Department         41 non-null     object
 5   Salary             40 non-null     float64
 6   Experience_Years   41 non-null     int64
 7   Performance_Score  40 non-null     float64
 8   Join_Date          41 non-null     object
 9   Gender             41 non-null     object
dtypes: float64(3), int64(2), object(5)
memory usage: 3.3+ KB

9. Descriptive Statistics

In [107]:
df.describe()

,Employee_ID,Age,Salary,Experience_Years,Performance_Score
count,41.000000,40.000000,40.000000,41.000000,40.000000
mean,20.975610,29.150000,80800.000000,5.951220,85.825000
std,11.938358,6.298351,71721.666433,5.258095,6.217789
min,1.000000,22.000000,43000.000000,1.000000,72.000000
25%,11.000000,25.000000,55750.000000,3.000000,82.000000
50%,21.000000,27.500000,64500.000000,4.000000,86.500000
75%,31.000000,31.000000,76750.000000,7.000000,90.000000
max,40.000000,52.000000,500000.000000,27.000000,97.000000

10. Select one column

In [108]:
df["Age"]

0     23.0
1     25.0
2     28.0
3     24.0
4     31.0
5     27.0
6     29.0
7     22.0
8     26.0
9     30.0
10     NaN
11    24.0
12    35.0
13    27.0
14    33.0
15    26.0
16    41.0
17    23.0
18    29.0
19    32.0
20    28.0
21    25.0
22    27.0
23    34.0
24    24.0
25    26.0
26    30.0
27    29.0
28    38.0
29    27.0
30    45.0
31    22.0
32    25.0
33    28.0
34    36.0
35    31.0
36    27.0
37    29.0
38    52.0
39    24.0
40    24.0
Name: Age, dtype: float64

11. Select Multiple columns

In [109]:
df[["Age", "Salary"]]

     Age    Salary
0   23.0   52000.0
1   25.0   48000.0
2   28.0   65000.0
3   24.0   56000.0
4   31.0   72000.0
5   27.0   68000.0
6   29.0   71000.0
7   22.0   45000.0
8   26.0   59000.0
9   30.0   75000.0
10   NaN   61000.0
11  24.0       NaN
12  35.0   98000.0
13  27.0   50000.0
14  33.0   83000.0
15  26.0   64000.0
16  41.0  125000.0
17  23.0   47000.0
18  29.0   70000.0
19  32.0   82000.0
20  28.0   54000.0
21  25.0   57000.0
22  27.0   67000.0
23  34.0  118000.0
24  24.0   53000.0
25  26.0   66000.0
26  30.0   76000.0
27  29.0   58000.0
28  38.0  110000.0
29  27.0   69000.0
30  45.0  150000.0
31  22.0   43000.0
32  25.0   60000.0
33  28.0   62000.0
34  36.0   92000.0
35  31.0   79000.0
36  27.0   60500.0
37  29.0   56500.0
38  52.0  500000.0
39  24.0   55000.0
40  24.0   55000.0

12. Select using loc

In [110]:
df.loc[0, "Age"]

np.float64(23.0)

13. Select using iloc

In [111]:
df.iloc[0,2] #Age is 3rd column

np.float64(23.0)

14. Filter rows

In [112]:
df[df["Age"]>30]

,Employee_ID,Name,Age,City,Department,Salary,Experience_Years,Performance_Score,Join_Date,Gender
4,5,Arjun,31.0,Chennai,Sales,72000.0,7,76.0,2026-02-10,Male
12,13,Kiran,35.0,Hyderabad,IT,98000.0,10,89.0,2026-03-24,Male
14,15,Manish,33.0,Pune,Finance,83000.0,8,NaN,2026-04-02,Male
16,17,Siddharth,41.0,Bengaluru,Management,125000.0,15,92.0,2026-04-11,Male
19,20,Tanya,32.0,Pune,IT,82000.0,8,94.0,2026-04-25,Female
23,24,Neha,34.0,Hyderabad,Management,118000.0,11,91.0,2026-05-17,Female
28,29,Naveen,38.0,Hyderabad,IT,110000.0,13,96.0,2026-06-05,Male
30,31,Om,45.0,Mumbai,Management,150000.0,20,88.0,2026-06-15,Male
34,35,Dhruv,36.0,Pune,Finance,92000.0,11,93.0,2026-07-04,Male
35,36,Lavanya,31.0,Mumbai,IT,79000.0,7,90.0,2026-07-09,Female
38,39,Rakesh,52.0,Chennai,Management,500000.0,27,97.0,2026-07-22,Male

15. Multiple conditions

In [113]:
df[(df["Salary"]>98000) & (df["Age"]>30)]

,Employee_ID,Name,Age,City,Department,Salary,Experience_Years,Performance_Score,Join_Date,Gender
16,17,Siddharth,41.0,Bengaluru,Management,125000.0,15,92.0,2026-04-11,Male
23,24,Neha,34.0,Hyderabad,Management,118000.0,11,91.0,2026-05-17,Female
28,29,Naveen,38.0,Hyderabad,IT,110000.0,13,96.0,2026-06-05,Male
30,31,Om,45.0,Mumbai,Management,150000.0,20,88.0,2026-06-15,Male
38,39,Rakesh,52.0,Chennai,Management,500000.0,27,97.0,2026-07-22,Male

16. Check missing values

In [114]:
df.isnull().sum()

Employee_ID          0
Name                 0
Age                  1
City                 1
Department           0
Salary               1
Experience_Years     0
Performance_Score    1
Join_Date            0
Gender               0
dtype: int64

17. Drop missing values

In [115]:
df.dropna()

,Employee_ID,Name,Age,City,Department,Salary,Experience_Years,Performance_Score,Join_Date,Gender
0,1,Aarav,23.0,Hyderabad,IT,52000.0,2,78.0,2026-01-12,Male
1,2,Diya,25.0,Bengaluru,HR,48000.0,3,84.0,2026-01-15,Female
2,3,Rohan,28.0,Pune,Finance,65000.0,5,91.0,2026-02-01,Male
3,4,Meera,24.0,Hyderabad,IT,56000.0,2,88.0,2026-02-03,Female
4,5,Arjun,31.0,Chennai,Sales,72000.0,7,76.0,2026-02-10,Male
5,6,Kavya,27.0,Bengaluru,IT,68000.0,4,93.0,2026-02-17,Female
6,7,Vikram,29.0,Mumbai,Finance,71000.0,6,81.0,2026-02-20,Male
7,8,Isha,22.0,Pune,HR,45000.0,1,74.0,2026-03-01,Female
8,9,Aditya,26.0,Hyderabad,Sales,59000.0,3,85.0,2026-03-07,Male
9,10,Sneha,30.0,Chennai,IT,75000.0,7,95.0,2026-03-11,Female
12,13,Kiran,35.0,Hyderabad,IT,98000.0,10,89.0,2026-03-24,Male
15,16,Nisha,26.0,Mumbai,IT,64000.0,3,90.0,2026-04-06,Female
16,17,Siddharth,41.0,Bengaluru,Management,125000.0,15,92.0,2026-04-11,Male
17,18,Riya,23.0,Chennai,Sales,47000.0,1,77.0,2026-04-15,Female
18,19,Harsh,29.0,Hyderabad,Finance,70000.0,5,86.0,2026-04-21,Male
19,20,Tanya,32.0,Pune,IT,82000.0,8,94.0,2026-04-25,Female
20,21,Kabir,28.0,Mumbai,HR,54000.0,5,80.0,2026-05-01,Male
21,22,Aisha,25.0,Bengaluru,Sales,57000.0,2,83.0,2026-05-05,Female
22,23,Dev,27.0,Chennai,IT,67000.0,4,88.0,2026-05-12,Male
23,24,Neha,34.0,Hyderabad,Management,118000.0,11,91.0,2026-05-17,Female
24,25,Yash,24.0,Pune,Finance,53000.0,2,75.0,2026-05-20,Male
25,26,Simran,26.0,Mumbai,IT,66000.0,3,89.0,2026-05-23,Female
26,27,Varun,30.0,Bengaluru,Sales,76000.0,7,84.0,2026-05-27,Male
27,28,Priya,29.0,Chennai,HR,58000.0,6,86.0,2026-06-01,Female
28,29,Naveen,38.0,Hyderabad,IT,110000.0,13,96.0,2026-06-05,Male
29,30,Maya,27.0,Pune,Finance,69000.0,4,90.0,2026-06-10,Female
30,31,Om,45.0,Mumbai,Management,150000.0,20,88.0,2026-06-15,Male
31,32,Sana,22.0,Bengaluru,HR,43000.0,1,72.0,2026-06-20,Female
32,33,Reyansh,25.0,Hyderabad,IT,60000.0,3,85.0,2026-06-24,Male
33,34,Aditi,28.0,Chennai,Sales,62000.0,5,87.0,2026-07-01,Female
34,35,Dhruv,36.0,Pune,Finance,92000.0,11,93.0,2026-07-04,Male
35,36,Lavanya,31.0,Mumbai,IT,79000.0,7,90.0,2026-07-09,Female
36,37,Aryan,27.0,Bengaluru,Sales,60500.0,4,82.0,2026-07-15,Male
37,38,Shruti,29.0,Hyderabad,HR,56500.0,5,88.0,2026-07-18,Female
38,39,Rakesh,52.0,Chennai,Management,500000.0,27,97.0,2026-07-22,Male
39,40,Divya,24.0,Pune,IT,55000.0,2,84.0,2026-07-29,Female
40,40,Divya,24.0,Pune,IT,55000.0,2,84.0,2026-07-29,Female

18. Fill missing values with MEAN

In [116]:
df["Age"]= df["Age"].fillna(df["Age"].mean())

19. Fill missing values with MEDIAN

In [117]:
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

20. Fill Missing Categorial values

In [118]:
df["City"] = df["City"].fillna(df["City"].mode()[0])
# [0] picks very 1st frequent element

21. Check Duplicates

In [119]:
df.duplicated().sum()

np.int64(1)

22. Drop the duplicates

In [120]:
df = df.drop_duplicates()

23. Unique values

In [121]:
df["Department"].unique()

array(['IT', 'HR', 'Finance', 'Sales', 'Management'], dtype=object)

24. Count unique values

In [122]:
df["Department"].nunique()

5

25. Value counts

In [123]:
df["Department"].value_counts()

Department
IT            13
Finance        8
Sales          8
HR             7
Management     4
Name: count, dtype: int64

26. Sort values

In [124]:
df.sort_values("Salary")

,Employee_ID,Name,Age,City,Department,Salary,Experience_Years,Performance_Score,Join_Date,Gender
31,32,Sana,22.00,Bengaluru,HR,43000.0,1,72.0,2026-06-20,Female
7,8,Isha,22.00,Pune,HR,45000.0,1,74.0,2026-03-01,Female
17,18,Riya,23.00,Chennai,Sales,47000.0,1,77.0,2026-04-15,Female
1,2,Diya,25.00,Bengaluru,HR,48000.0,3,84.0,2026-01-15,Female
13,14,Pooja,27.00,Hyderabad,HR,50000.0,4,82.0,2026-03-28,Female
0,1,Aarav,23.00,Hyderabad,IT,52000.0,2,78.0,2026-01-12,Male
24,25,Yash,24.00,Pune,Finance,53000.0,2,75.0,2026-05-20,Male
20,21,Kabir,28.00,Mumbai,HR,54000.0,5,80.0,2026-05-01,Male
39,40,Divya,24.00,Pune,IT,55000.0,2,84.0,2026-07-29,Female
3,4,Meera,24.00,Hyderabad,IT,56000.0,2,88.0,2026-02-03,Female
37,38,Shruti,29.00,Hyderabad,HR,56500.0,5,88.0,2026-07-18,Female
21,22,Aisha,25.00,Bengaluru,Sales,57000.0,2,83.0,2026-05-05,Female
27,28,Priya,29.00,Chennai,HR,58000.0,6,86.0,2026-06-01,Female
8,9,Aditya,26.00,Hyderabad,Sales,59000.0,3,85.0,2026-03-07,Male
32,33,Reyansh,25.00,Hyderabad,IT,60000.0,3,85.0,2026-06-24,Male
36,37,Aryan,27.00,Bengaluru,Sales,60500.0,4,82.0,2026-07-15,Male
10,11,Rahul,29.15,Mumbai,Sales,61000.0,4,79.0,2026-03-15,Male
33,34,Aditi,28.00,Chennai,Sales,62000.0,5,87.0,2026-07-01,Female
15,16,Nisha,26.00,Mumbai,IT,64000.0,3,90.0,2026-04-06,Female
11,12,Ananya,24.00,Bengaluru,Finance,64500.0,2,87.0,2026-03-18,Female
2,3,Rohan,28.00,Pune,Finance,65000.0,5,91.0,2026-02-01,Male
25,26,Simran,26.00,Mumbai,IT,66000.0,3,89.0,2026-05-23,Female
22,23,Dev,27.00,Chennai,IT,67000.0,4,88.0,2026-05-12,Male
5,6,Kavya,27.00,Bengaluru,IT,68000.0,4,93.0,2026-02-17,Female
29,30,Maya,27.00,Pune,Finance,69000.0,4,90.0,2026-06-10,Female
18,19,Harsh,29.00,Hyderabad,Finance,70000.0,5,86.0,2026-04-21,Male
6,7,Vikram,29.00,Mumbai,Finance,71000.0,6,81.0,2026-02-20,Male
4,5,Arjun,31.00,Chennai,Sales,72000.0,7,76.0,2026-02-10,Male
9,10,Sneha,30.00,Chennai,IT,75000.0,7,95.0,2026-03-11,Female
26,27,Varun,30.00,Bengaluru,Sales,76000.0,7,84.0,2026-05-27,Male
35,36,Lavanya,31.00,Mumbai,IT,79000.0,7,90.0,2026-07-09,Female
19,20,Tanya,32.00,Pune,IT,82000.0,8,94.0,2026-04-25,Female
14,15,Manish,33.00,Pune,Finance,83000.0,8,NaN,2026-04-02,Male
34,35,Dhruv,36.00,Pune,Finance,92000.0,11,93.0,2026-07-04,Male
12,13,Kiran,35.00,Hyderabad,IT,98000.0,10,89.0,2026-03-24,Male
28,29,Naveen,38.00,Hyderabad,IT,110000.0,13,96.0,2026-06-05,Male
23,24,Neha,34.00,Hyderabad,Management,118000.0,11,91.0,2026-05-17,Female
16,17,Siddharth,41.00,Bengaluru,Management,125000.0,15,92.0,2026-04-11,Male
30,31,Om,45.00,Mumbai,Management,150000.0,20,88.0,2026-06-15,Male
38,39,Rakesh,52.00,Chennai,Management,500000.0,27,97.0,2026-07-22,Male

27. Sort Descending

In [125]:
df.sort_values("Salary", ascending=False)

,Employee_ID,Name,Age,City,Department,Salary,Experience_Years,Performance_Score,Join_Date,Gender
38,39,Rakesh,52.00,Chennai,Management,500000.0,27,97.0,2026-07-22,Male
30,31,Om,45.00,Mumbai,Management,150000.0,20,88.0,2026-06-15,Male
16,17,Siddharth,41.00,Bengaluru,Management,125000.0,15,92.0,2026-04-11,Male
23,24,Neha,34.00,Hyderabad,Management,118000.0,11,91.0,2026-05-17,Female
28,29,Naveen,38.00,Hyderabad,IT,110000.0,13,96.0,2026-06-05,Male
12,13,Kiran,35.00,Hyderabad,IT,98000.0,10,89.0,2026-03-24,Male
34,35,Dhruv,36.00,Pune,Finance,92000.0,11,93.0,2026-07-04,Male
14,15,Manish,33.00,Pune,Finance,83000.0,8,NaN,2026-04-02,Male
19,20,Tanya,32.00,Pune,IT,82000.0,8,94.0,2026-04-25,Female
35,36,Lavanya,31.00,Mumbai,IT,79000.0,7,90.0,2026-07-09,Female
26,27,Varun,30.00,Bengaluru,Sales,76000.0,7,84.0,2026-05-27,Male
9,10,Sneha,30.00,Chennai,IT,75000.0,7,95.0,2026-03-11,Female
4,5,Arjun,31.00,Chennai,Sales,72000.0,7,76.0,2026-02-10,Male
6,7,Vikram,29.00,Mumbai,Finance,71000.0,6,81.0,2026-02-20,Male
18,19,Harsh,29.00,Hyderabad,Finance,70000.0,5,86.0,2026-04-21,Male
29,30,Maya,27.00,Pune,Finance,69000.0,4,90.0,2026-06-10,Female
5,6,Kavya,27.00,Bengaluru,IT,68000.0,4,93.0,2026-02-17,Female
22,23,Dev,27.00,Chennai,IT,67000.0,4,88.0,2026-05-12,Male
25,26,Simran,26.00,Mumbai,IT,66000.0,3,89.0,2026-05-23,Female
2,3,Rohan,28.00,Pune,Finance,65000.0,5,91.0,2026-02-01,Male
11,12,Ananya,24.00,Bengaluru,Finance,64500.0,2,87.0,2026-03-18,Female
15,16,Nisha,26.00,Mumbai,IT,64000.0,3,90.0,2026-04-06,Female
33,34,Aditi,28.00,Chennai,Sales,62000.0,5,87.0,2026-07-01,Female
10,11,Rahul,29.15,Mumbai,Sales,61000.0,4,79.0,2026-03-15,Male
36,37,Aryan,27.00,Bengaluru,Sales,60500.0,4,82.0,2026-07-15,Male
32,33,Reyansh,25.00,Hyderabad,IT,60000.0,3,85.0,2026-06-24,Male
8,9,Aditya,26.00,Hyderabad,Sales,59000.0,3,85.0,2026-03-07,Male
27,28,Priya,29.00,Chennai,HR,58000.0,6,86.0,2026-06-01,Female
21,22,Aisha,25.00,Bengaluru,Sales,57000.0,2,83.0,2026-05-05,Female
37,38,Shruti,29.00,Hyderabad,HR,56500.0,5,88.0,2026-07-18,Female
3,4,Meera,24.00,Hyderabad,IT,56000.0,2,88.0,2026-02-03,Female
39,40,Divya,24.00,Pune,IT,55000.0,2,84.0,2026-07-29,Female
20,21,Kabir,28.00,Mumbai,HR,54000.0,5,80.0,2026-05-01,Male
24,25,Yash,24.00,Pune,Finance,53000.0,2,75.0,2026-05-20,Male
0,1,Aarav,23.00,Hyderabad,IT,52000.0,2,78.0,2026-01-12,Male
13,14,Pooja,27.00,Hyderabad,HR,50000.0,4,82.0,2026-03-28,Female
1,2,Diya,25.00,Bengaluru,HR,48000.0,3,84.0,2026-01-15,Female
17,18,Riya,23.00,Chennai,Sales,47000.0,1,77.0,2026-04-15,Female
7,8,Isha,22.00,Pune,HR,45000.0,1,74.0,2026-03-01,Female
31,32,Sana,22.00,Bengaluru,HR,43000.0,1,72.0,2026-06-20,Female

28. Mean

In [126]:
print(df["Salary"].mean())

81037.5

29. Median

In [127]:
print(df["Salary"].median())

64750.0

30. Mode

In [128]:
print(df["Department"].mode())

0    IT
Name: Department, dtype: object

31. Standard deviation

In [129]:
print(df["Salary"].std())

71649.73450842791

32. Variance

In [130]:
print(df["Salary"].var())

5133684455.128205

33. Minimum and Maximum

In [131]:
df["Salary"].min()

43000.0

In [132]:
df["Salary"].max()

500000.0

34. GroupBy

In [133]:
df.groupby("Department")["Salary"].mean()

Department
Finance        70937.500000
HR             50642.857143
IT             71692.307692
Management    223250.000000
Sales          61812.500000
Name: Salary, dtype: float64

35. GroupBy Multiple Aggregations

In [134]:
df.groupby("Department")["Salary"].agg(["mean", "min", "max"])

                     mean       min       max
Department
Finance      70937.500000   53000.0   92000.0
HR           50642.857143   43000.0   58000.0
IT           71692.307692   52000.0  110000.0
Management  223250.000000  118000.0  500000.0
Sales        61812.500000   47000.0   76000.0

36. GroupBy Count

In [135]:
df.groupby("Department")["Salary"].count()

Department
Finance        8
HR             7
IT            13
Management     4
Sales          8
Name: Salary, dtype: int64

In [136]:
df.groupby("Department")["Salary"].size()

Department
Finance        8
HR             7
IT            13
Management     4
Sales          8
Name: Salary, dtype: int64

37. Correlation Matrix

In [137]:
df.corr(numeric_only=True)

,Employee_ID,Age,Salary,Experience_Years,Performance_Score
Employee_ID,1.000000,0.300422,0.295488,0.307856,0.195582
Age,0.300422,1.000000,0.800203,0.990731,0.589931
Salary,0.295488,0.800203,1.000000,0.841619,0.447511
Experience_Years,0.307856,0.990731,0.841619,1.000000,0.566432
Performance_Score,0.195582,0.589931,0.447511,0.566432,1.000000

38. Convert Date column

In [138]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"])
df["Join_Date"]

0    2026-01-12
1    2026-01-15
2    2026-02-01
3    2026-02-03
4    2026-02-10
5    2026-02-17
6    2026-02-20
7    2026-03-01
8    2026-03-07
9    2026-03-11
10   2026-03-15
11   2026-03-18
12   2026-03-24
13   2026-03-28
14   2026-04-02
15   2026-04-06
16   2026-04-11
17   2026-04-15
18   2026-04-21
19   2026-04-25
20   2026-05-01
21   2026-05-05
22   2026-05-12
23   2026-05-17
24   2026-05-20
25   2026-05-23
26   2026-05-27
27   2026-06-01
28   2026-06-05
29   2026-06-10
30   2026-06-15
31   2026-06-20
32   2026-06-24
33   2026-07-01
34   2026-07-04
35   2026-07-09
36   2026-07-15
37   2026-07-18
38   2026-07-22
39   2026-07-29
Name: Join_Date, dtype: datetime64[ns]

39. Extract Year

In [139]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"])
df["Join_Year"] = df["Join_Date"].dt.year
df["Join_Year"]

0     2026
1     2026
2     2026
3     2026
4     2026
5     2026
6     2026
7     2026
8     2026
9     2026
10    2026
11    2026
12    2026
13    2026
14    2026
15    2026
16    2026
17    2026
18    2026
19    2026
20    2026
21    2026
22    2026
23    2026
24    2026
25    2026
26    2026
27    2026
28    2026
29    2026
30    2026
31    2026
32    2026
33    2026
34    2026
35    2026
36    2026
37    2026
38    2026
39    2026
Name: Join_Year, dtype: int32

40. Extract Month

In [140]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"])
df["Join_Month"] = df["Join_Date"].dt.month
df["Join_Month"]

0     1
1     1
2     2
3     2
4     2
5     2
6     2
7     3
8     3
9     3
10    3
11    3
12    3
13    3
14    4
15    4
16    4
17    4
18    4
19    4
20    5
21    5
22    5
23    5
24    5
25    5
26    5
27    6
28    6
29    6
30    6
31    6
32    6
33    7
34    7
35    7
36    7
37    7
38    7
39    7
Name: Join_Month, dtype: int32

41. Create New column

In [141]:
df["Bonus"] = df["Salary"] *0.2

42. Apply Function

In [142]:
df["Age_Group"] = df["Age"].apply(
    lambda x : "Young" if x < 30 else "Explerienced"
)

43. Rename Column

In [143]:
df = df.rename(columns = {"Salary": "Annual_salary"})

44. Drop colummn

In [144]:
df = df.drop(columns=["Bonus"])

45. Detect Outliers using IQR

In [145]:
Q1 = df["Annual_salary"].quantile(0.25)
Q3 = df["Annual_salary"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df["Annual_salary"] < lower) |
    (df["Annual_salary"] > upper)
]
outliers

,Employee_ID,Name,Age,City,Department,Annual_salary,Experience_Years,Performance_Score,Join_Date,Gender,Join_Year,Join_Month,Age_Group
16,17,Siddharth,41.0,Bengaluru,Management,125000.0,15,92.0,2026-04-11,Male,2026,4,Explerienced
23,24,Neha,34.0,Hyderabad,Management,118000.0,11,91.0,2026-05-17,Female,2026,5,Explerienced
28,29,Naveen,38.0,Hyderabad,IT,110000.0,13,96.0,2026-06-05,Male,2026,6,Explerienced
30,31,Om,45.0,Mumbai,Management,150000.0,20,88.0,2026-06-15,Male,2026,6,Explerienced
38,39,Rakesh,52.0,Chennai,Management,500000.0,27,97.0,2026-07-22,Male,2026,7,Explerienced

46. Filter without outliers

In [146]:
df_clean = df[
    (df["Annual_salary"] >= lower) &
    (df["Annual_salary"] <= upper)
]

47. Simple Pivot table

In [147]:
pd.pivot_table(
    df,
    values = "Annual_salary",
    index = "Department",
    aggfunc = "mean"
)

            Annual_salary
Department
Finance      70937.500000
HR           50642.857143
IT           71692.307692
Management  223250.000000
Sales        61812.500000

48. Crosstab

In [148]:
pd.crosstab(df["Department"], df["Gender"])

Gender      Female  Male
Department
Finance          2     6
HR               6     1
IT               8     5
Management       1     3
Sales            3     5

49. Save Cleaned Dataset

In [149]:
df.to_csv("cleaned_data.csv", index=False)

50. Quick EDA Summary

In [150]:
print(df.shape)

(40, 13)

In [151]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 40 entries, 0 to 39
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        40 non-null     int64
 1   Name               40 non-null     object
 2   Age                40 non-null     float64
 3   City               40 non-null     object
 4   Department         40 non-null     object
 5   Annual_salary      40 non-null     float64
 6   Experience_Years   40 non-null     int64
 7   Performance_Score  39 non-null     float64
 8   Join_Date          40 non-null     datetime64[ns]
 9   Gender             40 non-null     object
 10  Join_Year          40 non-null     int32
 11  Join_Month         40 non-null     int32
 12  Age_Group          40 non-null     object
dtypes: datetime64[ns](1), float64(3), int32(2), int64(2), object(5)
memory usage: 4.1+ KB
None

In [152]:
print(df.describe())

       Employee_ID        Age  Annual_salary  Experience_Years  \
count    40.000000  40.000000      40.000000         40.000000
mean     20.500000  29.278750   81037.500000          6.050000
min       1.000000  22.000000   43000.000000          1.000000
25%      10.750000  25.000000   56375.000000          3.000000
50%      20.500000  28.000000   64750.000000          4.500000
75%      30.250000  31.000000   76750.000000          7.000000
max      40.000000  52.000000  500000.000000         27.000000
std      11.690452   6.242769   71649.734508          5.286412

       Performance_Score            Join_Date  Join_Year  Join_Month
count          39.000000                   40       40.0   40.000000
mean           85.871795  2026-04-26 12:36:00     2026.0    4.425000
min            72.000000  2026-01-12 00:00:00     2026.0    1.000000
25%            82.000000  2026-03-14 00:00:00     2026.0    3.000000
50%            87.000000  2026-04-28 00:00:00     2026.0    4.500000
75%            90.000000  2026-06-11 06:00:00     2026.0    6.000000
max            97.000000  2026-07-29 00:00:00     2026.0    7.000000
std             6.291931                  NaN        0.0    1.838164

In [153]:
print(df.isnull().sum())

Employee_ID          0
Name                 0
Age                  0
City                 0
Department           0
Annual_salary        0
Experience_Years     0
Performance_Score    1
Join_Date            0
Gender               0
Join_Year            0
Join_Month           0
Age_Group            0
dtype: int64

In [154]:
print(df.duplicated().sum())

0

In [155]:
print(df["Department"].value_counts())

Department
IT            13
Finance        8
Sales          8
HR             7
Management     4
Name: count, dtype: int64

In [156]:
print(df.corr(numeric_only=True))

                   Employee_ID       Age  Annual_salary  Experience_Years  \
Employee_ID           1.000000  0.300422       0.295488          0.307856
Age                   0.300422  1.000000       0.800203          0.990731
Annual_salary         0.295488  0.800203       1.000000          0.841619
Experience_Years      0.307856  0.990731       0.841619          1.000000
Performance_Score     0.195582  0.589931       0.447511          0.566432
Join_Year                  NaN       NaN            NaN               NaN
Join_Month            0.986195  0.299667       0.270977          0.301208

                   Performance_Score  Join_Year  Join_Month
Employee_ID                 0.195582        NaN    0.986195
Age                         0.589931        NaN    0.299667
Annual_salary               0.447511        NaN    0.270977
Experience_Years            0.566432        NaN    0.301208
Performance_Score           1.000000        NaN    0.207180
Join_Year                        NaN        NaN         NaN
Join_Month                  0.207180        NaN    1.000000